# Generated by Django 2.2.3 on 2020-03-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestWebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Page',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='people',
            name='Psex',
            field=models.CharField(default='man', max_length=10),
        ),
    ]
